# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jordan Van Wyk
email: jordanvanwyk@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  All about Jordan Van Wyk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jordanvanwyk.com" # the base hostname & protocol for your site
twitter_username: jordanvw_
github_username:  jordanvanwyk

# Build settings
markdown: kramdown
